import Head from 'next/head'
import Image from 'next/image'
import InputTasks from '../components/InputTasks'
import ListTasks from '../components/ListTasks'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PERN setup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InputTasks/>
      <ListTasks/>

      
    </div>
  )
}
